# Generated by Django 5.2.4 on 2025-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project.', max_length=200)),
                ('description', models.TextField(help_text='A detailed description of the project.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the project was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the project was last updated.')),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly slug generated from the project name.', max_length=250, null=True, unique=True)),
                ('image', models.ImageField(blank=True, help_text='An optional image representing the project.', null=True, upload_to='project_images/')),
                ('live_url', models.URLField(blank=True, help_text='Optional URL to the live demo of the project.', null=True)),
                ('github_url', models.URLField(blank=True, help_text="Optional URL to the project's GitHub repository.", null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
